// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenericPayload {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Menggunakan Unix Timestamp (lebih cepat di-parse)
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
