[package]
name = "data_processor_engine"
version = "1.0.0"
edition = "2021"

[lib]
name = "data_engine"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.7" # Untuk pemrosesan paralel
once_cell = "1.18"

[profile.release]
opt-level = 3
lto = "fat"
strip = true